version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: [dependencies, maintenance]
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: uv
    directory: /
    labels: [dependencies, maintenance]
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      development-tools:
        patterns: ['*']
