-- Exported from ResInsight 2026-09-09 09:22:04
WELSEGS
-- Well          Dep 1          Tlen 1         Vol 1     Len&Dep     PresDrop
   P09NOAUTO     8325.00000     8325.00000     1*        ABS         'HF-'    /
-- First Seg     Last Seg     Branch No     Outlet Seg     Length         Depth Change     Diam        Rough    
-- Segments on main bore
   2             2            1             1              8335.00000     8335.00000       0.50000     0.0000328 /
   3             3            1             2              8360.00000     8360.00000       0.50000     0.0000328 /
   4             4            1             3              8400.00000     8400.00000       0.50000     0.0000328 /
/
COMPSEGS
-- Name     
   P09NOAUTO /
-- I     J     K     Branch no     Start Length     End Length     Dir Pen     End Range     Connection Depth
   5     5     1     1             8326.00000       8345.00000      /
   5     5     2     1             8345.00000       8375.00000      /
   5     5     3     1             8375.00000       8424.00000      /
/
